Revert "Eliminar navbar por error"
This r
rodri@WIN-C2ANEVBHN6Q MINGW64 ~/Documents/GitHub/TECNICAS/PRACTICA_1_PMO (feature_1)
$ git revert 4b3269d180d79343af098d012b31b288eaf59b4d
Auto-merging index.html
CONFLICT (content): Merge conflict in index.html
error: could not revert 4b3269d... Eliminar navbar por error
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git revert --continue".
hint: You can instead skip this commit with "git revert --skip".
hint: To abort and get back to the state before "git revert",
hint: run "git revert --abort".
hint: Disable this message with "git config set advice.mergeConflict false"

rodri@WIN-C2ANEVBHN6Q MINGW64 ~/Documents/GitHub/TECNICAS/PRACTICA_1_PMO (feature_1|REVERTING)
$ git fetch

rodri@WIN-C2ANEVBHN6Q MINGW64 ~/Documents/GitHub/TECNICAS/PRACTICA_1_PMO (feature_1|REVERTING)
$ git status
On branch feature_1
Your branch is up to date with 'origin/feature_1'.

You are currently reverting commit 4b3269d.
  (fix conflicts and run "git revert --continue")
  (use "git revert --skip" to skip this patch)
  (use "git revert --abort" to cancel the revert operation)

Unmerged paths:
  (use "git restore --staged <file>..." to unstage)
  (use "git add <file>..." to mark resolution)
        both modified:   index.html

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        logs/

no changes added to commit (use "git add" and/or "git commit -a")

rodri@WIN-C2ANEVBHN6Q MINGW64 ~/Documents/GitHub/TECNICAS/PRACTICA_1_PMO (feature_1|REVERTING)
$ cat index.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<link rel="stylesheet" href="styles/style.css">
<title>INICIO P01</title>
<linki href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
<p>Esto es un párrafo</p>
<h1>Esto es un header</h1>

<<<<<<< HEAD
<table>
<tr>
<td>1,1</td>
<td>1,2</td>
</tr>
<tr>
<td>2,1</td>
<td>2,2</td>
</tr>
</table>

=======
<nav class="navbar navbar-expand-sm bg-light">
<div class="container-fluid">
<ul class="navbar-nav">
<li class="nav-item">
<a class="nav-link" href="page_a.html">Page A</a>
</li>
<li class="nav-item">
<a class="nav-link" href="page_b.html">Page B</a>
</li>
</ul>
</div>
</nav>
>>>>>>> parent of 4b3269d (Eliminar navbar por error)
</body>
</html>everts commit 4b3269d180d79343af098d012b31b288eaf59b4d.